pub const CLIBS: &[&str] = &[
    "assert", "ctype", "errno", "limits", "math", "stdarg", "stdbool", "stddef", "stdint", "stdio",
    "stdlib", "string", "time", "setjmp", "signal",
];
pub const CTYPES: &[&str] = &[
    "char",
    "short",
    "int",
    "long",
    "float",
    "double",
    "jmp_buf",
    "unsigned",
    "bool",
    "void",
    "char",
    "short",
    "int",
    "long",
    "float",
    "double",
    "unsigned",
    "bool",
    "va_list",
    "FILE",
    "ptrdiff_t",
    "size_t",
    "wchar_t",
    "int8_t",
    "int16_t",
    "int32_t",
    "int64_t",
    "uint8_t",
    "uint16_t",
    "uint32_t",
    "uint64_t",
    "clock_t",
    "time_t",
];
pub const CCONST: &[&str] = &[
    "RAND_MAX", "BUFSIZ", "_IOLBF", "EOF", "SEEK_SET", "SEEK_END", "SEEK_CUR", "errno",
    // limits.h
    "INT_MAX", "LONG_MAX", "SIZE_MAX", // signal.h
    "SIGABRT", "SIGFPE", "SIGILL", "SIGINT", "SIGSEGV", "SIGTERM", "SIG_DFL", "SIG_IGN",
];

pub const CFUNCS: &[&str] = &[
    "atoi",
    "strncat",
    "islower",
    "isspace",
    "acos",
    "floor",
    "round",
    "strrchr",
    "tolower",
    "toupper",
    "strncmp",
    "setjmp",
    "longjmp",
    "strcat",
    "floorf",
    "sqrtf",
    "ceilf",
    "sinf",
    "cosf",
    "fabs",
    "strtoull",
    "strncpy",
    "rewind",
    "qsort",
    "strchr",
    "fgets",
    "log",
    "sqrt",
    "assert",
    "vasprintf",
    "fputs",
    "rename",
    "setvbuf",
    "isalpha",
    "strstr",
    "remove",
    "calloc",
    "cos",
    "exit",
    "exp",
    "fclose",
    "feof",
    "fgetc",
    "fopen",
    "fprintf",
    "fputc",
    "fseek",
    "ftell",
    "fread",
    "free",
    "fwrite",
    "localtime",
    // "malloc",
    "memcpy",
    "memset",
    "printf",
    "puts",
    "realloc",
    "roundf",
    "ungetc",
    "putchar",
    "scanf",
    "abort",
    "memmove",
    "srand",
    "rand",
    "getc",
    // signal.h
    "signal",
    // ...
    "getchar",
    "putc",
    "fflush",
    "ferror",
    "sin",
    "snprintf",
    "strcmp",
    "strcpy",
    "strlen",
    "stdin",
    "stdout",
    "stderr",
    "time",
    "tmpfile",
    "va_end",
    "va_start",
    "vfprintf",
    "vprintf",
    "vsnprintf",
    "vsprintf",
    "sprintf",
    "strftime",
    "strerror",
    "sscanf",
    "isdigit",
];
