pub const CLIBS: &[&str] = &[
    "assert", "ctype", "errno", "limits", "math", "stdarg", "stdbool", "stddef", "stdint", "stdio",
    "stdlib", "string", "time", "setjmp",
];
pub const CTYPES: &[&str] = &[
    "char",
    "short",
    "int",
    "long",
    "float",
    "double",
    "unsigned",
    "bool",
    "void",
    "char",
    "short",
    "int",
    "long",
    "float",
    "double",
    "unsigned",
    "bool",
    "va_list",
    "FILE",
    "ptrdiff_t",
    "size_t",
    "wchar_t",
    "int8_t",
    "int16_t",
    "int32_t",
    "int64_t",
    "uint8_t",
    "uint16_t",
    "uint32_t",
    "uint64_t",
    "clock_t",
    "time_t",
];
